# -*- coding: utf-8 -*-
"""Uber Trips Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179V9YQQjvmV0J5KiNlH0X2YIH1Ks5KH5

## **1. Project Title and Introduction**
"""

# ================================================================
#                    UBER TRIPS DATA ANALYSIS
#                   Internship Project - Vcodez
#                     Author: Suriyaprakash
# ================================================================

print("Uber Trips Data Analysis - Internship Project (Vcodez)")
print("Author: Suriyaprakash")

"""## **2. Install & Import Required Libraries**"""

!pip install plotly ipywidgets seaborn --quiet
from google.colab import output
output.enable_custom_widget_manager()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from ipywidgets import interact, Dropdown
from IPython.display import display, clear_output

"""## **3. Load Dataset**"""

import pandas as pd

# Load data
df = pd.read_csv("uber_trips_chennai.csv", parse_dates=["timestamp"])
df.head()

"""## **4. Basic Info & Structure**"""

# Inspect data structure
df.shape, df.info()

"""## **5. Summary Statistics**"""

df.describe(include='all').T

"""## **6. Missing Values**"""

df.isna().sum().sort_values(ascending=False)

"""## **7. Descriptive Statistics for Distance, Fare & Trip Duration**"""

df[["distance_km", "fare_inr", "trip_duration_min"]].describe()

"""## **8. Top 10 Most Frequent Pickup Zones and Drop Zones**"""

df["pickup_zone"].value_counts().head(10)
df["drop_zone"].value_counts().head(10)

"""## **9. Missing Values Count for Each Column**"""

df.isnull().sum()

"""## **10. Total Number of Duplicate Rows in the Dataset**"""

df.duplicated().sum()

"""## **11. Count of Unique Values in Each Column**"""

df.nunique()

"""## **12. Frequency Count of All Unique Rows in the Dataset**"""

df.value_counts()

"""## **13. Filling Missing Values Using Forward Fill (FFill) Method**"""

df.fillna(method='ffill',inplace=True)

"""## **14. Extracting Date, Hour, Weekday, and Month from Timestamp**"""

df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour
df["weekday"] = df["timestamp"].dt.day_name()
df["month"] = df["timestamp"].dt.month_name()

"""## **15. Preview of First 10 Rows of the Updated Dataset**"""

df.head(10)

"""## **16. Zone Distribution**"""

df["pickup_zone"].value_counts()

"""## **17. Adding Vehicle Type Column and Checking Distribution**"""

import numpy as np

# Randomly assign vehicle types
df["vehicle_type"] = np.random.choice(["Uber Go", "Auto", "UberXL", "Bike"], size=len(df), p=[0.4, 0.3, 0.2, 0.1])

# Check that it worked
df["vehicle_type"].value_counts()

"""## **18. Saving the Updated Dataset with Vehicle Type Added**"""

df.to_csv("uber_trips_chennai_cleaned.csv", index=False)
print("✅ Vehicle type column added and saved!")

"""## **19. Reloading Dataset and Reapplying All Cleaning & Feature Engineering Steps**

This describes that you're reloading the CSV and applying the same transformations (FFill, date extraction, vehicle type assignment, etc.)
"""

import pandas as pd
import numpy as np

# Load data from the original CSV
df = pd.read_csv("uber_trips_chennai_cleaned.csv", parse_dates=["timestamp"])

# Fill missing values using forward fill, as done previously
df.fillna(method='ffill', inplace=True)

# Extract date and time components, as done previously
df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour
df["weekday"] = df["timestamp"].dt.day_name()
df["month"] = df["timestamp"].dt.month_name()

# Randomly assign vehicle types, as done previously
df["vehicle_type"] = np.random.choice(["Uber Go", "Auto", "UberXL", "Bike"], size=len(df), p=[0.4, 0.3, 0.2, 0.1])

print("DataFrame 'df' has been reloaded and prepared with all previous transformations.")
display(df.head())

"""## **20. Advanced Data Cleaning, Outlier Removal & Feature Engineering**

This covers everything you're doing:

✔ Filling missing numeric values
✔ Dropping missing coordinates
✔ Removing duplicates
✔ Filtering unrealistic outliers
✔ Creating time-based features
✔ Creating derived metrics
✔ Assigning vehicle types
✔ Saving the cleaned dataset
"""

import pandas as pd
import numpy as np

df = pd.read_csv("uber_trips_chennai_cleaned.csv", parse_dates=["timestamp"])

# Fill missing numeric values
df["fare_inr"].fillna(df["fare_inr"].median(), inplace=True)
df["distance_km"].fillna(df["distance_km"].median(), inplace=True)

# Drop rows missing coordinates
df.dropna(subset=["pickup_lat","pickup_lng"], inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Filter unrealistic outliers
df = df[(df["distance_km"] <= 40) & (df["fare_inr"] <= 2000)]

# Time-based features
df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour
df["weekday"] = df["timestamp"].dt.day_name()
df["month"] = df["timestamp"].dt.month_name()

# Derived metrics
df["fare_per_km"] = df["fare_inr"] / df["distance_km"]
df["is_weekend"] = df["weekday"].isin(["Saturday","Sunday"])

# Vehicle type column
df["vehicle_type"] = np.random.choice(["Uber Go","Auto","UberXL","Bike"], size=len(df))

df.to_csv("uber_trips_cleaned.csv", index=False)
df.head()

"""## **21. Installing Streamlit for Interactive Dashboard Development**"""

!pip install streamlit -q

"""## **22. Creating the Streamlit Dashboard Script (uber_dashboard.py)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile uber_dashboard.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# df = pd.read_csv("uber_trips_cleaned.csv")
# 
# st.title("Uber Trips Dashboard - Chennai")
# 
# st.subheader("Key Metrics")
# col1, col2, col3 = st.columns(3)
# col1.metric("Total Trips", df.shape[0])
# col2.metric("Total Revenue (INR)", f"{df['fare_inr'].sum():,.2f}")
# col3.metric("Average Fare per Trip (INR)", f"{df['fare_inr'].mean():,.2f}")
# 
# col4, col5, col6 = st.columns(3)
# col4.metric("Average Distance per Trip (km)", f"{df['distance_km'].mean():,.2f}")
# col5.metric("Average Trip Duration (min)", f"{df['trip_duration_min'].mean():,.2f}")
# col6.metric("Trips with Shared Ride", df['is_shared'].sum())
# 
# st.subheader("Trip Distribution")
# fig = px.histogram(df, x="hour", title="Trips by Hour of Day")
# st.plotly_chart(fig)
# 
# fig2 = px.histogram(df, x="weekday", title="Trips by Weekday")
# st.plotly_chart(fig2)
# 
# fig3 = px.histogram(df, x="vehicle_type", title="Trips by Vehicle Type")
# st.plotly_chart(fig3)
# 
# st.subheader("Zone Analysis")
# col7, col8 = st.columns(2)
# with col7:
#     st.write("**Most Frequent Pickup Zones**")
#     st.dataframe(df["pickup_zone"].value_counts().head())
# with col8:
#     st.write("**Most Frequent Drop Zones**")
#     st.dataframe(df["drop_zone"].value_counts().head())
# 
# st.subheader("Payment & Platform Analysis")
# col9, col10 = st.columns(2)
# with col9:
#     st.write("**Payment Type Distribution**")
#     st.dataframe(df["payment_type"].value_counts())
# with col10:
#     st.write("**Platform Distribution**")
#     st.dataframe(df["platform"].value_counts())

"""## **23. Installing ipywidgets & Plotly and Enabling Widget Support in Google Colab**"""

!pip install ipywidgets plotly
from google.colab import output
output.enable_custom_widget_manager()

"""## **24.  Downloading the Cleaned Dataset to Local Machine**"""

from google.colab import files
files.download('uber_trips_chennai_cleaned.csv')

"""## **25. Uploading, Cleaning, and Exporting the Fully Cleaned Uber Trips Dataset**"""

import pandas as pd

# Upload your CSV
from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

# Additional cleaning
# Convert timestamp if present
if "timestamp" in df.columns:
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

# Convert date column if present
if "date" in df.columns:
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Drop rows with missing timestamp
if "timestamp" in df.columns:
    df = df.dropna(subset=["timestamp"])

# Remove remaining NaN values
df = df.dropna()

# Remove duplicates
df = df.drop_duplicates()

# Fix numeric types
numeric_cols = ["distance_km", "fare_inr", "fare_per_km", "hour"]
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Drop rows again if conversion created NaN
df = df.dropna()

# Save cleaned CSV
df.to_csv("uber_trips_fully_cleaned.csv", index=False)

# Download
files.download("uber_trips_fully_cleaned.csv")

"""## **26. Renaming Columns to Clean and Readable Titles for Analysis & Dashboarding**"""

df.columns

df = df.rename(columns={
    "trip_id": "Trip ID",
    "timestamp": "Timestamp",
    "hour": "Hour",
    "weekday": "Weekday",
    "month": "Month",
    "pickup_zone": "Pickup Zone",
    "drop_zone": "Drop Zone",
    "pickup_lat": "Pickup Latitude",
    "pickup_lng": "Pickup Longitude",
    "drop_lat": "Drop Latitude",
    "drop_lng": "Drop Longitude",
    "distance_km": "Distance (Km)",
    "fare_inr": "Fare (INR)",
    "trip_duration_min": "Trip Duration (Min)",
    "vehicle_type": "Vehicle Type",
    "payment_type": "Payment Type",
    "platform": "Platform",
    "is_shared": "Is Shared",
    "fare_per_km": "Fare per Km",
    "is_weekend": "Is Weekend", # Added comma here
    "driver_id": "Driver ID",
    "driver_name": "Driver Name",
    "driver_phone": "Driver Phone",
    "driver_email": "Driver Email",
    "driver_license": "Driver License",
    "driver_rating": "Driver Rating",
    "customer_id": "Customer ID",
    "date": "Date",
    "city": "City"
})

df.columns

"""## **27. Rounding Numerical Columns for Consistent Formatting and Readability**"""

df["Distance (Km)"] = df["Distance (Km)"].round(2)
df["Fare (INR)"] = df["Fare (INR)"].round(2)
df["Pickup Latitude"] = df["Pickup Latitude"].round(4)
df["Pickup Longitude"] = df["Pickup Longitude"].round(4)
df["Drop Latitude"] = df["Drop Latitude"].round(4)
df["Drop Longitude"] = df["Drop Longitude"].round(4)

"""## **28. Saving and Downloading the Final Cleaned Dataset to CSV**"""

df.to_csv("uber_trips_final_cleaned.csv", index=False)

from google.colab import files
files.download("uber_trips_final_cleaned.csv")

"""## **29. Extracting Time Features and Plotting Trips by Hour of Day**"""

df["Timestamp"].min(), df["Timestamp"].max()
df["Hour"] = df["Timestamp"].dt.hour
df["Weekday"] = df["Timestamp"].dt.day_name()

df["Hour"].value_counts().sort_index().plot(kind="bar", title="Trips by Hour of Day")

"""## **30. Distribution of Trips Across Months (Countplot)**"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='Month',data=df)
plt.title(" Distrubution of Months")
plt.show()

"""## **31.  Distribution of Trips Across Weekdays (Countplot)**"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='Weekday', data=df)
plt.title("Distribution of Weekdays")
plt.show()

"""## **32. Saving the Fully Cleaned Dataset to CSV**"""

df.to_csv("uber_trips_fully_cleaned.csv", index=False)
print("Cleaned dataset saved ")

"""## **33. Bar Chart of Trip Counts by Weekday**"""

df["Weekday"].value_counts().plot(kind="bar", figsize=(10,4), title="Trips by Weekday", color="orange")

"""## **34. Distribution of Trips by Hour of Day (Countplot), Trips by Weekday (Ordered Countplot), Trips by Vehicle Type (Countplot), Correlation Matrix of Numerical Features**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,4))
sns.countplot(x=df["Hour"])
plt.title("Trips by Hour of Day")
plt.show()

plt.figure(figsize=(10,4))
sns.countplot(x=df["Weekday"], order=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
plt.xticks(rotation=45)
plt.title("Trips by Weekday")
plt.show()

plt.figure(figsize=(10,4))
sns.countplot(x=df["Vehicle Type"])
plt.title("Trips by Vehicle Type")
plt.show()

df.corr(numeric_only=True)

"""## **35. Demand Heatmap: Trips by Hour vs Weekday**"""

pivot = df.pivot_table(index="Hour", columns="Weekday", values="Trip ID", aggfunc="count")
plt.figure(figsize=(12,6))
sns.heatmap(pivot, cmap="Blues")
plt.title("Demand Heatmap (Hour vs Weekday)")
plt.show()

"""## **36. Fare per Km Comparison Across Vehicle Types (Boxplot)**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'Fare per Km' column exists and is correctly named
# Check if base columns for calculation are present (they should be after previous renames)
if 'Fare (INR)' in df.columns and 'Distance (Km)' in df.columns:
    # Create 'fare_per_km' (temporary name if needed)
    if 'fare_per_km' not in df.columns and 'Fare per Km' not in df.columns:
        df['fare_per_km'] = df['Fare (INR)'] / df['Distance (Km)']

    # If 'fare_per_km' exists but 'Fare per Km' doesn't, rename it
    if 'fare_per_km' in df.columns and 'Fare per Km' not in df.columns:
        df = df.rename(columns={'fare_per_km': 'Fare per Km'})
    # If it was already named 'Fare per Km' from a previous run (e.g. from an earlier cell),
    # we don't need to do anything.

plt.figure(figsize=(8,4))
sns.boxplot(x=df["Vehicle Type"], y=df["Fare per Km"], palette="Set2")
plt.title("Fare Per KM by Vehicle Type")
plt.show()

"""## **37.  Interactive Dashboard: Filter Trips by Vehicle Type (Plotly + ipywidgets)**"""

import pandas as pd
import plotly.express as px
from ipywidgets import interact, Dropdown

df = pd.read_csv("uber_trips_cleaned.csv")

@interact(
    vehicle=Dropdown(options=["All"] + sorted(df["vehicle_type"].unique()), description="Vehicle:")
)
def update(vehicle):
    # Apply filter
    filtered = df if vehicle == "All" else df[df["vehicle_type"] == vehicle]

    # Chart 1: Trips by Hour
    fig1 = px.histogram(filtered, x="hour", title="Trips by Hour")
    fig1.show()

    # Chart 2: Trips by Weekday
    fig2 = px.histogram(filtered, x="weekday", title="Trips by Weekday")
    fig2.show()

    # Chart 3: Trips by Vehicle Type
    fig3 = px.histogram(filtered, x="vehicle_type", title="Trips by Vehicle Type")
    fig3.show()

"""## **38. Importing Display Utility for Rendering Outputs in Jupyter Notebook**"""

from IPython.display import display

"""## **39. Advanced Interactive Dashboard with Multi-Filter (Vehicle Type + Weekday) Using Plotly & ipywidgets**"""

import pandas as pd
import plotly.express as px
from ipywidgets import interact, Dropdown
from IPython.display import display

df = pd.read_csv("uber_trips_cleaned.csv")

# Ensure weekday is string for filtering
df["weekday"] = df["weekday"].astype(str)

@interact(
    vehicle=Dropdown(options=["All"] + sorted(df["vehicle_type"].unique()), description="Vehicle:"),
    weekday=Dropdown(options=["All"] + sorted(df["weekday"].unique()), description="Weekday:")
)
def update(vehicle, weekday):

    # Filter dataset
    filtered = df.copy()
    if vehicle != "All":
        filtered = filtered[filtered["vehicle_type"] == vehicle]
    if weekday != "All":
        filtered = filtered[filtered["weekday"] == weekday]

    # CHART 1 — Trips by Hour (Blue)
    fig1 = px.histogram(
        filtered,
        x="hour",
        title=f"Trips by Hour ({vehicle}, {weekday})",
        color_discrete_sequence=["#1f77b4"]  # Blue
    )
    display(fig1)

    # CHART 2 — Trips by Weekday (Green)
    fig2 = px.histogram(
        filtered,
        x="weekday",
        title=f"Trips by Weekday ({vehicle}, {weekday})",
        color_discrete_sequence=["#2ca02c"]  # Green
    )
    display(fig2)

    # CHART 3 — Trips by Vehicle Type (Orange)
    fig3 = px.histogram(
        filtered,
        x="vehicle_type",
        title=f"Trips by Vehicle Type ({vehicle}, {weekday})",
        color_discrete_sequence=["#ff7f0e"]  # Orange
    )
    display(fig3)

"""## **40. Pickup and Drop-off Location Maps**"""

# Pickup Map
fig4 = px.scatter_mapbox(
    df,
    lat="pickup_lat",
    lon="pickup_lng",
    color="pickup_zone",
    zoom=10,
    title="Pickup Locations Map",
    height=600
)

fig4.update_layout(mapbox_style="open-street-map")
fig4.show()

# Drop Map
fig5 = px.scatter_mapbox(
    df,
    lat="drop_lat",
    lon="drop_lng",
    color="drop_zone",
    zoom=10,
    title="Drop Locations Map",
    height=600
)

fig5.update_layout(mapbox_style="open-street-map")
fig5.show()

"""## **41. Distance vs Fare Scatter Plot**"""

fig6 = px.scatter(
    df,
    x="distance_km",
    y="fare_inr",
    color="vehicle_type",
    title="Distance vs Fare Scatter Plot",
    labels={"distance_km": "Distance (km)", "fare_inr": "Fare (INR)"},
    height=500
)

fig6.show()

"""## **42. Advanced Interactive Uber Trips Dashboard**"""

import pandas as pd
import plotly.express as px
from ipywidgets import interact, Dropdown
from IPython.display import display, clear_output

df = pd.read_csv("uber_trips_chennai_cleaned.csv")

df["weekday"] = df["weekday"].astype(str)

BLUE = ["#1f77b4"]   # your selected blue color

@interact(
    vehicle=Dropdown(options=["All"] + sorted(df["vehicle_type"].unique()), description="Vehicle:"),
    weekday=Dropdown(options=["All"] + sorted(df["weekday"].unique()), description="Weekday:")
)
def dashboard(vehicle, weekday):

    clear_output(wait=True)
    print("📊 Uber Trips Dashboard — Filtered Results")

    # Filtering
    temp = df.copy()
    if vehicle != "All":
        temp = temp[temp["vehicle_type"] == vehicle]

    if weekday != "All":
        temp = temp[temp["weekday"] == weekday]

    print(f"Total trips: {len(temp)}")

    # Trips by Hour (Blue)
    fig1 = px.bar(
        temp.groupby("hour").size().reset_index(name="count"),
        x="hour", y="count",
        title="Trips by Hour",
        color_discrete_sequence=BLUE
    )
    display(fig1)

    # Trips by Weekday (Blue)
    fig2 = px.bar(
        temp.groupby("weekday").size().reset_index(name="count"),
        x="weekday", y="count",
        title="Trips by Weekday",
        color_discrete_sequence=BLUE
    )
    display(fig2)

    # Trips by Vehicle Type (Blue)
    fig3 = px.bar(
        temp.groupby("vehicle_type").size().reset_index(name="count"),
        x="vehicle_type", y="count",
        title="Trips by Vehicle Type",
        color_discrete_sequence=BLUE
    )
    display(fig3)

    # Distance vs Fare Scatter Plot (Blue)
    fig4 = px.scatter(
        temp,
        x="distance_km",
        y="fare_inr",
        title="Distance vs Fare (Scatter Plot)",
        color_discrete_sequence=BLUE
    )
    display(fig4)